wsgi/pratosocial/apps/recipe/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from apps.core.views import UserRecipeListView
from apps.recipe.views import RecipeDetailView, RecipeListView, RecipeEditView, RecipeBookCreateView, RecipeCreateView, RecipeDeleteView, RecipeBookDeleteView, RecipePDFView, RecipeBookPDFView, \
    RecipeBookEditView

urlpatterns = patterns('',
    url(r'^$', RecipeListView.as_view(), name='recipe_list'),
    url(r'^deleta/receita/(?P<pk>\d+)/$', RecipeDeleteView.as_view(), name='recipe_delete'),
    url(r'^deleta/livro/(?P<pk>\d+)/$', RecipeBookDeleteView.as_view(), name='recipe_book_delete'),
    url(r'^recentes/$', RecipeListView.as_view(), name='recipe_recent_list'),
    url(r'^comentadas/$', RecipeListView.as_view(), name='recipe_comment_list'),
    url(r'^visitadas/$', RecipeListView.as_view(), name='recipe_visit_list'),
    url(r'^detalhe/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', RecipeDetailView.as_view(), name='recipe_detail'),
    url(r'^nova/$', RecipeCreateView.as_view(), name='new_recipe'),
    url(r'^editar/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', RecipeEditView.as_view(), name='edit_recipe'),
    url(r'^livro-de-receitas/$', RecipeBookCreateView.as_view(), name='new_recipe_book'),
    url(r'^livro-de-receitas/editar/(?P<pk>\d+)/$', RecipeBookEditView.as_view(), name='recipebook_edit'),
    url(r'^livro-de-receitas/(?P<pk>\d+)/$', UserRecipeListView.as_view(), name='recipe_book_detail'),
    url(r'^adiciona-receita/(?P<recipe_pk>\d+)/(?P<recipe_book_pk>\d+)/$', 'apps.recipe.ajax.add_recipe', name='add_recipe'),
    url(r'^deletar-foto-receita/(?P<photo_recipe_pk>\d+)/$', 'apps.recipe.ajax.del_photo_recipe', name='del_photo_recipe'),
    url(r'^deletar-foto-instagram-receita/(?P<photo_insta_pk>\d+)/$', 'apps.recipe.ajax.del_photo_insta', name='del_photo_insta'),
    url(r'^receita-pdf/(?P<pk>\d+)/$', RecipePDFView.as_view(), name="recipe_pdf"),
    url(r'^livro-pdf/(?P<pk>\d+)/$', RecipeBookPDFView.as_view(), name="recipe_book_pdf"),
    url(r'^get-photos-instagram/$', 'apps.recipe.ajax.get_photo_instagram', name='get_photo_instagram'),

)

wsgi/pratosocial/pratosocial/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.core.views import HomeView, LogoutView
from apps.website.views import ContactView
from pratosocial import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^chefes/', include('apps.core.urls')),
    url(r'^receitas/', include('apps.recipe.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/post/$', 'apps.recipe.views.post_comment'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^contato/', ContactView.as_view(), name='contact'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    # url('', include('django.contrib.auth.urls', namespace='auth'))

)
# Arquivos estáticos e de media
urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

admin.site.site_header = 'Prato Social'

wsgi/pratosocial/apps/core/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
import os
import random
import string
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.utils.text import slugify
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from apps.recipe.models import Recipe

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernanbuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, username, password):
        user = self.create_user(username, email, password=password)
        user.is_superuser = True
        user.save(using=self._db)
        return user

def update_filename(instance, filename):
    path = "uploads/user/"
    fname = filename.split('.')
    format = slugify(fname[0]) + ''.join([random.SystemRandom().choice(''.join(string.digits)) for i in range(8)]) + '.' + fname[-1]
    return os.path.join(path, format)

class User(AbstractBaseUser):
    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    email = models.EmailField(verbose_name='Email', max_length=255, unique=True, db_index=True)
    username = models.CharField('Nome', max_length=50)
    is_active = models.BooleanField('Ativo?', default=True)
    is_member = models.BooleanField('Membro?', default=True)
    is_superuser = models.BooleanField('Administrador?', default=False)
    created_date = models.DateTimeField('Criado em', default=datetime.now)
    photo = models.ImageField('Foto', upload_to=update_filename, blank=True, null=True)
    photo_thumb = ImageRatioField('photo', '65x65')
    state = models.CharField('Estado', max_length=50, choices=UF_CHOICES, blank=True, null=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['email']

    def get_photo_thumb(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (65, 65),
            'box': self.photo_thumb,
            'crop': True,
            'detail': True,
            }).url

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_superuser

wsgi/pratosocial/apps/recipe/models.py
# -*- coding: utf-8 -*-
import string
import random
import urllib
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify
from django_comments import Comment
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from datetime import datetime
from django.core.files import File
import os
from taggit.managers import TaggableManager


def update_filename(instance, filename):
    date = datetime.today()
    if type(instance) is CommentWithPic:
        path = "uploads/comments/"+str(date.year)+"/"+str(date.month)+"/"
    elif type(instance) is Recipe or PhotoRecipe or PhotoInstagram:
        path = "uploads/receitas/"+str(date.year)+"/"+str(date.month)+"/"
    elif type(instance) is RecipeBook:
        path = "uploads/livro-receitas/"+str(date.year)+"/"+str(date.month)+"/"
    else:
        path = "uploads/outros/"
    fname = filename.split('.')
    format = slugify(fname[0]) + ''.join([random.SystemRandom().choice(''.join(string.digits)) for i in range(8)]) + '.' + fname[-1]
    return os.path.join(path, format)


class CommentWithPic(Comment):
    image = models.ImageField(upload_to=update_filename, null=True, blank=True)
    image_thumb = ImageRatioField('image', '135x100')

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'

    def get_image_thumb(self):
        return get_thumbnailer(self.image).get_thumbnail({
            'size': (135, 100),
            'box': self.image_thumb,
            'crop': True,
            'detail': True,
            }).url


class Recipe(models.Model):
    user = models.ForeignKey('core.User')
    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', help_text='Breve descrição da receita')
    ingredients = models.TextField('Ingredientes')
    method_of_preparation = models.TextField('Modo de preparo')
    time_of_preparation = models.CharField('Tempo de preparo', max_length=20)
    produce = models.CharField('Redimento', max_length=20)
    photo = models.ImageField('Foto', upload_to=update_filename)
    photo_260x140 = ImageRatioField('photo', '260x140')
    photo_260x300 = ImageRatioField('photo', '260x300')
    photo_162x150 = ImageRatioField('photo', '162x150')
    photo_235x151 = ImageRatioField('photo', '235x151')
    photo_450x450 = ImageRatioField('photo', '450x450')
    slug = models.SlugField(max_length=150, blank=True)
    tags = TaggableManager()
    sugestion_day = models.BooleanField('Sugestão do dia', default=False)
    status = models.BooleanField(default=True)
    comments = generic.GenericRelation(Comment, object_id_field="object_pk")
    visits = models.IntegerField(default=0)
    published_at = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)

    class Meta:
        verbose_name = 'Receita'
        verbose_name_plural = 'Receitas'

    def __unicode__(self):
        return self.name

    def imageAdmin(self):
        if self.photo:
            im = get_thumbnailer(self.photo).get_thumbnail({'size': (135, 135), 'box': self.photo_162x150})
            return '<img src="{0}" />'.format(im.url)
        else:
            return 'Sem Imagem'

    imageAdmin.is_safe = True
    imageAdmin.allow_tags = True
    imageAdmin.short_description = u'Imagem'

    def get_image_260x140(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (260, 240),
            'box': self.photo_260x140,
            'crop': True,
            'detail': True,
            }).url

    def get_image_260x300(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (260, 300),
            'box': self.photo_260x300,
            'crop': True,
            'detail': True,
            }).url

    def get_image_162x150(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (162, 150),
            'box': self.photo_162x150,
            'crop': True,
            'detail': True,
            }).url

    def get_image_235x151(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (235, 151),
            'box': self.photo_235x151,
            'crop': True,
            'detail': True,
            }).url

    def get_image_450x450(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (450, 450),
            'box': self.photo_450x450,
            'crop': True,
            'detail': True,
            }).url

class PhotoRecipe(models.Model):
    photo = models.ImageField(verbose_name="Foto", upload_to=update_filename, blank=True)
    photo_thumb = ImageRatioField('photo', '135x100')
    recipe = models.ForeignKey(Recipe, verbose_name="Receita")

    class Meta:
        verbose_name = 'Foto de Receita'
        verbose_name_plural = 'Fotos de Receitas'
        ordering = ['recipe']

    def __unicode__(self):
        return u'%s' % str(self.photo).split('/')[-1]

    def image_thumb(self):
        if self.photo:
            try:
                im = get_thumbnailer(self.photo).get_thumbnail({
                    'size': (135, 100),
                    'box': self.photo_thumb
                })
                return im.url
            except:
                return ''

        return ''

    def imagemAdmin(self):
        if self.photo:
            try:
                im = get_thumbnailer(self.photo).get_thumbnail({
                    'size': (135, 90),
                    'box': self.photo_thumb
                })
                return '<img src="{0}" />'.format(im.url)
            except:
                return ''
        return ''

    imagemAdmin.is_safe = True
    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Imagem'


class PhotoInstagram(models.Model):
    image_file = models.ImageField(verbose_name="Foto Instagram", upload_to=update_filename, blank=True)
    image_url = models.URLField()
    photo_thumb = ImageRatioField('image_file', '135x100')
    recipe = models.ForeignKey(Recipe, verbose_name="Receita")

    def save(self, *args, **kwargs):
        get_remote_image(self)

        super(PhotoInstagram, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Foto de Receita'
        verbose_name_plural = 'Fotos de Receitas'
        ordering = ['recipe']

    def __unicode__(self):
        return u'%s' % str(self.image_file).split('/')[-1]

    def image_thumb(self):
        if self.image_file:
            try:
                im = get_thumbnailer(self.image_file).get_thumbnail({
                    'size': (135, 100),
                    'box': self.photo_thumb
                })
                return im.url
            except:
                return ''

        return ''

    def imagemAdmin(self):
        if self.image_file:
            try:
                im = get_thumbnailer(self.image_file).get_thumbnail({
                    'size': (135, 90),
                    'box': self.photo_thumb
                })
                return '<img src="{0}" />'.format(im.url)
            except:
                return ''
        return ''

    imagemAdmin.is_safe = True
    imagemAdmin.allow_tags = True
    imagemAdmin.short_description = u'Imagem'


def get_remote_image(self):
    if self.image_url and not self.image_file:
        result = urllib.urlretrieve(self.image_url)
        self.image_file.save(
                os.path.basename(self.image_url),
                File(open(result[0]))
                )
        self.save()


class RecipeBook(models.Model):
    name = models.CharField('Nome', max_length=200)
    recipes = models.ManyToManyField(Recipe, verbose_name='Receitas', blank=True, null=True)
    photo = models.ImageField('Foto', upload_to=update_filename, blank=True, null=True)
    photo_thumb = ImageRatioField('photo', '190x190')
    description = models.TextField('Descrição', blank=True, null=True, help_text='Breve descrição da livro')
    user = models.ForeignKey('core.User', verbose_name='Usuário')
    status = models.BooleanField(default=True)

    def get_photo_thumb(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (190, 190),
            'box': self.photo_thumb,
            'crop': True,
            'detail': True,
            }).url

    class Meta:
        ordering = ('name',)
        verbose_name = 'Livro de receita'
        verbose_name_plural = 'Livros de receitas'

    def __unicode__(self):
        return self.name


def recipe_pre_save(signal, instance, sender, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

signals.pre_save.connect(recipe_pre_save, sender=Recipe)

wsgi/pratosocial/templates/recipe/recipe_list.html
{% extends 'elements/base.html' %}
{% block content %}


<section class="block-in">

    <div class="row">
        <div class="large-8 medium-8 small-12 columns ">
            <div class="bread">
                <ul class="breadcrumbs">
                    <li><a href="{% url 'home' %}">Início</a></li>
                    <li class="current"><a href="#">Receitas</a></li>
                </ul>
            </div>

            <div class="block widget show-for-small">
                <form action="" class="form-search">
                    <div class="row collapse">
                        <div class="small-9 columns">
                            <input type="text" placeholder="Pesquisar receitas ou chefes">
                        </div>
                        <div class="small-3 columns">
                            <a href="#" class="button postfix"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                </form>
            </div>

            <section class="block widget top-recipes">
                {% if request.GET.q %}
                <h4 class="box-title fa fa-search">Resultado de <span>"{{ request.GET.q  }}"</span></h4>
                {% endif %}
                <ul class="recipe-list-top-recipes small-block-grid-1 medium-block-grid-3 large-block-grid-3">
                    {% for recipe in object_list %}
                    <li>
                        <div class="top-recipe img-transition">
                            <div class="img">
                                <a href="{% url 'recipe_detail' recipe.slug recipe.pk %}">
                                    <img src="{{ recipe.get_image_235x151 }}"
                                         alt="{{ recipe.name }}">
                                </a>
                            </div>
                            <div class="info">
                                <a href="{% url 'recipe_detail' recipe.slug recipe.pk %}">
                                    <h4>{{ recipe.name }}</h4>
                                </a>

                                <p class="chef">Por: {{ recipe.user.username }}</p>
                                <a href="{% url 'recipe_detail' recipe.slug recipe.pk %}" class="btn-see-recipe">Ver receita</a>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>

                {% if is_paginated %}
                <hr>
                <ul class="pagination pages">
                    {% if page_obj.has_previous %}
                        <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">◀</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% ifequal num page_obj.number %}
                            <li><a href="" class="current">{{ num }}</a></li>
                        {% else %}
                            {% if num <= page_obj.number|add:2 and num >= page_obj.number|add:-2 %}
                                <li><a href="?page={{ num }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ num }}</a></li>
                            {% endif %}
                        {% endifequal %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="arrow "><a href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">▶</a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </section>

        </div>

        <div class="large-4 medium-4 small-12 columns ">
            <div class="block widget hide-for-small">
                <div class="block widget hide-for-small">
                    <div class="form-search">
                        <input type="radio" name="tipo-busca" value="Receitas" id="receitas-chk" checked><label for="receitas-chk">Receitas</label>
                        <input type="radio" name="tipo-busca" value="Chefes" id="chefes-chk"><label for="chefes-chk">Chefes</label>

                        <div class="row collapse">
                            <div class="small-9 columns">
                                <input name="q" id="id_q" type="text" placeholder="Pesquisar receitas ou chefes">
                            </div>
                            <div class="small-3 columns">
                                <button onclick="search();" class="button postfix"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% include 'elements/sidebar_chef_recipe.html' %}
            {% include 'elements/sidebar_social.html' %}
        </div>
    </div>
</section>

{% endblock %}
{% block extrajs %}
<script type="text/javascript">
    $('#id_q').bind('keypress', function(e) {
        if (e.keyCode == 13) {
            search();
        }
    });
    function search(){
        var tipo_busca = $('input[name="tipo-busca"]:checked').val();
        var q = $('input[name="q"]').val();
        if(tipo_busca == 'Receitas'){
            window.location.href = '{% url 'recipe_list' %}?q='+q;
        }
        if(tipo_busca == 'Chefes'){
            window.location.href = '{% url 'user_list' %}?q='+q;
        }
    }
</script>
{% endblock %}

wsgi/pratosocial/templates/recipe/recipebook_form.html
{% extends 'elements/base.html' %}
{% load widget_tweaks %}
{% block title %}Prato Social - {% if object %}Editar{% else %}Criar{% endif %} Livro de receitas{% endblock %}
{% block content %}

<section class="block-in">
    {% include 'elements/messages.html' %}
    <section class="dashboard row">
        <div class="large-3 medium-3 small-12 columns ">
            <div class="sidebar">
                <div class="user-chef">
                    <div class="item-top-chefs">
                        <a href="{% url 'dashboard' request.user.pk %}">
                            {% if request.user.get_photo_thumb %}
                            <img src="{{ request.user.get_photo_thumb }}" alt="{{ request.user.username }}">
                            {% else %}
                            <img src="{{ STATIC_URL }}img/icons/user.png" alt="{{ request.user.username }}">
                            {% endif %}
                            <p class="name">{{ request.user.username }}</p>
                            {% if request.user.state %}
                            <p class="city">{{ request.user.get_state_display }}</p>
                            {% endif %}
                        </a>
                        <div class="clearfix"></div>
                    </div>
                    <div class="item-list-chef">
                        <div class="box recipe">
                            <a href="" data-tooltip aria-haspopup="true" class="has-tip" title="Receitas">
                                <p class="title"><i class="fa fa-file-text-o"></i></p>
                                <p class="value">{{ request.user.recipe_set.count }}</p>
                            </a>
                        </div>
                        <div class="box photos">
                            <a href="" data-tooltip aria-haspopup="true" class="has-tip" title="Livro de receitas">
                                <p class="title"><i class="fa fa-book"></i></p>
                                <p class="value">{{ request.user.recipebook_set.count }}</p>
                            </a>
                        </div>
                        <div class="box recipe-book">
                            <a href="" data-tooltip aria-haspopup="true" class="has-tip" title="Comentários">
                                <p class="title"><i class="fa fa-comments"></i></p>
                                <p class="value">{{ request.user.comment_comments.count }}</p>
                            </a>

                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="menu-sidebar">
                    <ul class="sidebar-menu">
                        <li><a href="{% url 'dashboard' request.user.pk %}">Perfil</a></li>
                        {% if request.user == request.user %}
                        <li><a href="{% url 'edit_user' request.user.pk %}">Configurações</a></li>
                        {% endif %}
                        <li><a href="{% url 'user_recipe_list' request.user.pk %}">Receitas</a></li>
                        <li><a href="{% url 'user_recipebook_list' request.user.pk %}">Livro de receitas</a></li>
                    </ul>

                </div>
            </div>
        </div>

        <div class="large-9 medium-9 small-12 columns ">
            <div class="content-dash">

                        <section class="main-dash">
                            <section class="block widget dashboard-header">
                                <div class="row">
                                    <div class="large-12 medium-12 small-12 columns">
                                        <h4 class="box-title fa fa-pencil-square-o">Adicionar <span>livro de receita</span></h4>
                                    </div>
                                </div>
                            </section>

                            <section class="block widget content-recentes">
                                    <form action="{% if object %}{% url 'recipebook_edit' object.id %}
{% else %}{% url 'new_recipe_book' %}{% endif %}" enctype='multipart/form-data' method="POST" accept-charset="utf-8" data-abide>
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="large-12 medium-12 columns">
                                                <label>Nome
                                                    <small>*</small>
                                                    {{ form.name|attr:'required' }}
                                                </label>
                                                <small class="error">Digite o nome da receita</small>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="large-6 medium-6 small-12 columns">
                                                <label>Descrição
                                                    <small>*</small>
                                                    {{ form.description|attr:'required' }}
                                                </label>
                                            </div>
                                        </div>
                                         <div class="row">
                                            <div class="large-12 medium-12 columns">
                                                <label>Foto
                                                    {{ form.photo }}
                                                </label>
                                            </div>
                                        </div>
                                        <button type="submit" class="button small radius">Salvar</button>
                                    </form>
                            </section>


                        </section>




            </div>

        </div>

    </section>
</section>

{% endblock %}
{% block extrajs %}
{% load staticfiles %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
{% endblock %}