wsgi/pratosocial/pratosocial/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.core.views import HomeView, LogoutView
from apps.website.views import ContactView
from pratosocial import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^chefes/', include('apps.core.urls')),
    url(r'^receitas/', include('apps.recipe.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/post/$', 'apps.recipe.views.post_comment'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^contato/', ContactView.as_view(), name='contact'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    # url('', include('django.contrib.auth.urls', namespace='auth'))

)
# Arquivos estáticos e de media
urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

admin.site.site_header = 'Prato Social'

wsgi/pratosocial/apps/core/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
import os
import random
import string
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.utils.text import slugify
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from apps.recipe.models import Recipe

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernanbuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, username, password):
        user = self.create_user(username, email, password=password)
        user.is_superuser = True
        user.save(using=self._db)
        return user

def update_filename(instance, filename):
    path = "uploads/user/"
    fname = filename.split('.')
    format = slugify(fname[0]) + ''.join([random.SystemRandom().choice(''.join(string.digits)) for i in range(8)]) + '.' + fname[-1]
    return os.path.join(path, format)

class User(AbstractBaseUser):
    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    email = models.EmailField(verbose_name='Email', max_length=255, unique=True, db_index=True)
    username = models.CharField('Nome', max_length=50)
    is_active = models.BooleanField('Ativo?', default=True)
    is_member = models.BooleanField('Membro?', default=True)
    is_superuser = models.BooleanField('Administrador?', default=False)
    created_date = models.DateTimeField('Criado em', default=datetime.now)
    photo = models.ImageField('Foto', upload_to=update_filename, blank=True, null=True)
    photo_thumb = ImageRatioField('photo', '65x65')
    state = models.CharField('Estado', max_length=50, choices=UF_CHOICES, blank=True, null=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['email']

    def get_photo_thumb(self):
        return get_thumbnailer(self.photo).get_thumbnail({
            'size': (65, 65),
            'box': self.photo_thumb,
            'crop': True,
            'detail': True,
            }).url

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_superuser

wsgi/pratosocial/apps/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.core.models import User


class SigninForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')
    password1 = forms.CharField(required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(required=True, widget=forms.PasswordInput())

    def clean(self):
        password1 = self.data.get("signin-password1")
        password2 = self.data.get("signin-password2")

        if password1 and password1 != password2:
            raise forms.ValidationError("Senhas não conferem!")

        return self.cleaned_data

    def save(self, commit=True):
        user = super(SigninForm, self).save(commit=False)
        user.set_password(self.data["signin-password1"])
        user.is_active = True
        user.is_member = True
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField(label=('Email'))
    password = forms.CharField(label=('Password'), widget=forms.PasswordInput)
    remember_me = forms.CheckboxInput()

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'photo', 'state']
    username = forms.CharField(label='Nome')

wsgi/pratosocial/apps/recipe/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from audioop import reverse

from django import http
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils.html import escape
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST

import django_comments
from django_comments import signals
from django_comments.views.utils import next_redirect, confirmation_view

from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, UpdateView, CreateView, ListView, DeleteView
from easy_pdf.views import PDFTemplateView
from apps.core.models import User
from apps.recipe.forms import RecipeForm, RecipeBookForm, CommentFormWithPic
from apps.recipe.models import Recipe, RecipeBook, PhotoRecipe, PhotoInstagram


class RecipePDFView(PDFTemplateView):
    model = Recipe
    template_name = "recipe/recipe_pdf.html"

    def get_context_data(self, **kwargs):
        context = super(RecipePDFView, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            context['recipe'] = Recipe.objects.get(pk=self.kwargs['pk'])

        return context


class RecipeBookPDFView(PDFTemplateView):
    model = Recipe
    template_name = "recipe/recipe_book_pdf.html"

    def get_context_data(self, **kwargs):
        context = super(RecipeBookPDFView, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            context['recipe_book'] = RecipeBook.objects.get(pk=self.kwargs['pk'])

        return context


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipe/recipe_list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(RecipeListView, self).get_context_data(**kwargs)
        context['top_chefs'] = User.objects.filter(is_active=True).annotate(num_recipes=Count('recipe'), num_recipe_book=Count('recipebook')).order_by('-num_recipes')[:2]
        context['visited_recipes'] = Recipe.objects.filter(status=True).order_by('-visits')[:2]
        return context

    def get_queryset(self):
        q = self.request.GET.get('q')
        if 'visitadas' in self.request.path:
            object_list = Recipe.objects.filter(status=True).order_by('-visits')
        elif 'comentadas' in self.request.path:
            object_list = Recipe.objects.annotate(comment_count=Count('comments')).filter(status=True).order_by('-comment_count')
        else:
            object_list = Recipe.objects.filter(status=True).order_by('-published_at')
        if q:
            object_list = object_list.filter(Q(name__icontains=q) | Q(user__username__icontains=q) | Q(tags__name__in=[q]))

        return object_list

class RecipeCreateView(CreateView):
    model = Recipe
    form_class = RecipeForm

    @method_decorator(login_required(login_url='/'))
    def dispatch(self, *args, **kwargs):
        return super(RecipeCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        recipe = Recipe()
        recipe.name = form.cleaned_data['name']
        recipe.description = form.cleaned_data['description']
        recipe.ingredients = form.cleaned_data['ingredients']
        recipe.method_of_preparation = form.cleaned_data['method_of_preparation']
        recipe.produce = form.cleaned_data['produce']
        recipe.time_of_preparation = form.cleaned_data['time_of_preparation']
        recipe.photo = form.cleaned_data['photo']
        recipe.tags = form.cleaned_data['tags']
        recipe.status = True
        recipe.user = self.request.user
        recipe.save()
        file_list = form.cleaned_data['images']
        try:
            if file_list[0]:
                for photo in file_list:
                    photo_recipe = PhotoRecipe()
                    photo_recipe.photo = photo
                    photo_recipe.recipe = recipe
                    photo_recipe.save()
        except:
            pass
        try:
            instagram_photo_list = self.request.POST.getlist('photo_instagram[]')
            if instagram_photo_list[0]:
                for image_url in instagram_photo_list:
                    photo_insta = PhotoInstagram()
                    photo_insta.image_url = image_url
                    photo_insta.recipe = recipe
                    photo_insta.save()
        except:
            pass

        messages.success(self.request, 'Receita criado com sucesso!')
        return redirect('dashboard', pk=recipe.user.pk)

    def form_invalid(self, form):
        if 'photo' in form.errors:
            messages.error(self.request, 'O campo foto de destaque é obrigatório.')
        else:
            messages.error(self.request, 'Os campos com * são obrigatórios.')
        return self.render_to_response(self.get_context_data(form=form))


class RecipeDetailView(DetailView):
    model = Recipe

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)
        context['top_chefs'] = User.objects.filter(is_active=True).annotate(num_recipes=Count('recipe'), num_recipe_book=Count('recipebook')).order_by('-num_recipes')[:2]
        context['visited_recipes'] = Recipe.objects.filter(status=True).order_by('-visits')[:2]
        try:
            context['recipe_book_list'] = RecipeBook.objects.filter(user=self.request.user).order_by('-name')
        except:
            pass
        return context

    def get_object(self, queryset=None):
        object = super(RecipeDetailView, self).get_object()
        object.visits += 1
        object.save()
        return object


class RecipeEditView(UpdateView):
    model = Recipe
    form_class = RecipeForm

    @method_decorator(login_required(login_url='/'))
    def dispatch(self, *args, **kwargs):
        return super(RecipeEditView, self).dispatch(*args, **kwargs)

    def get_object(self, *args, **kwargs):
        object = super(RecipeEditView, self).get_object(*args, **kwargs)
        if object.user != self.request.user:
            raise Http404
        return object

    def form_valid(self, form):
        obj = form.save()
        file_list = form.cleaned_data['images']
        try:
            if file_list[0]:
                for photo in file_list:
                    photo_recipe = PhotoRecipe()
                    photo_recipe.photo = photo
                    photo_recipe.recipe = obj
                    photo_recipe.save()
        except:
            pass
        try:
            instagram_photo_list = self.request.POST.getlist('photo_instagram[]')
            if instagram_photo_list[0]:
                for image_url in instagram_photo_list:
                    photo_insta = PhotoInstagram()
                    photo_insta.image_url = image_url
                    photo_insta.recipe = obj
                    photo_insta.save()
        except:
            pass
        messages.success(self.request, 'Receita modificada com sucesso!')
        return redirect('dashboard', pk=obj.user.pk)

    def form_invalid(self, form):
        if 'photo' in form.errors:
            messages.error(self.request, 'O campo foto de destaque é obrigatório.')
        else:
            messages.error(self.request, 'Os campos com * são obrigatórios.')
        return self.render_to_response(self.get_context_data(form=form))

class RecipeDeleteView(DeleteView):
    model = Recipe

    def get_object(self, queryset=None):
        obj = super(RecipeDeleteView, self).get_object()
        if not obj.user == self.request.user:
            raise Http404
        return obj

    def get_success_url(self):
        messages.success(self.request, 'Receita deletada com sucesso!')
        return u'/chefes/%d/' % self.object.user.pk


class RecipeBookCreateView(CreateView):
    model = RecipeBook
    form_class = RecipeBookForm

    @method_decorator(login_required(login_url='/'))
    def dispatch(self, *args, **kwargs):
        return super(RecipeBookCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        recipe_book = RecipeBook()
        recipe_book.name = form.cleaned_data['name']
        recipe_book.description = form.cleaned_data['description']
        recipe_book.photo = form.cleaned_data['photo']
        recipe_book.status = True
        recipe_book.user = self.request.user
        recipe_book.save()
        messages.success(self.request, 'Livro de receitas criado com sucesso!')
        return redirect('dashboard', pk=recipe_book.user.pk)

    def form_invalid(self, form):
        if 'description' in form.errors:
            messages.error(self.request, 'O campo descrição é obrigatório.')
        return self.render_to_response(self.get_context_data(form=form))


class RecipeBookEditView(UpdateView):
    model = RecipeBook
    form_class = RecipeBookForm

    @method_decorator(login_required(login_url='/'))
    def dispatch(self, *args, **kwargs):
        return super(RecipeBookEditView, self).dispatch(*args, **kwargs)

    def get_object(self, *args, **kwargs):
        object = super(RecipeBookEditView, self).get_object(*args, **kwargs)
        if object.user != self.request.user:
            raise Http404
        return object

    def form_valid(self, form):
        obj = form.save()
        messages.success(self.request, 'Livro de receitas modificada com sucesso!')
        return redirect('dashboard', pk=obj.user.pk)

    def form_invalid(self, form):
        if 'description' in form.errors:

wsgi/pratosocial/templates/elements/footer.html
<footer>
    <div class="footer">
        <div class="row">
            <div class="large-2 medium-2 small-12 columns hide-for-small">
                {% if 'detalhe' in request.path %}
                    <img src="{{ STATIC_URL }}img/icons/logo-interna.png" height="49" width="270" alt="">
                {% else %}
                    <img src="{{ STATIC_URL }}img/icons/logo-home.png" height="49" width="270" alt="">
                {% endif %}
            </div>

            <div class="large-10 medium-10 small-12 columns">
                <ul class="menu-footer">
                    <li class="hide-for-small">
                        <a href="{% url 'recipe_recent_list' %}">Receitas recentes</a>
                        <a href="{% url 'recipe_visit_list' %}">Receitas Top</a>
                        <a href="{% url 'recipe_comment_list' %}">Receitas mais comentadas</a>
                    </li>
                    <li class="hide-for-small">
                        <a href="{% url 'user_list' %}">Top Chefs</a>
                        <a href="{% url 'user_list' %}?letra=a">A</a>
                        <a href="{% url 'user_list' %}?letra=b">B</a>
                        <a href="{% url 'user_list' %}?letra=c">C</a>
                        <a href="{% url 'user_list' %}?letra=d">D</a>
                        <a href="{% url 'user_list' %}?letra=e">E</a>
                        <a href="{% url 'user_list' %}?letra=f">F</a>
                        <a href="{% url 'user_list' %}?letra=g">G</a>
                        <a href="{% url 'user_list' %}?letra=h">H</a>
                        <a href="{% url 'user_list' %}?letra=i">I</a>
                        <a href="{% url 'user_list' %}?letra=j">J</a>
                        <a href="{% url 'user_list' %}?letra=k">K</a>
                        <a href="{% url 'user_list' %}?letra=l">L</a>
                        <a href="{% url 'user_list' %}?letra=m">M</a>
                        <a href="{% url 'user_list' %}?letra=n">N</a>
                        <a href="{% url 'user_list' %}?letra=o">O</a>
                        <a href="{% url 'user_list' %}?letra=p">P</a>
                        <a href="{% url 'user_list' %}?letra=q">Q</a>
                        <a href="{% url 'user_list' %}?letra=r">R</a>
                        <a href="{% url 'user_list' %}?letra=s">S</a>
                        <a href="{% url 'user_list' %}?letra=t">T</a>
                        <a href="{% url 'user_list' %}?letra=u">U</a>
                        <a href="{% url 'user_list' %}?letra=v">V</a>
                        <a href="{% url 'user_list' %}?letra=w">W</a>
                        <a href="{% url 'user_list' %}?letra=x">X</a>
                        <a href="{% url 'user_list' %}?letra=y">Y</a>
                        <a href="{% url 'user_list' %}?letra=z">Z</a>
                    </li>
                    <li>{% if not user.is_authenticated %}
                        <a href="" data-reveal-id="modal-cadastrar">Cadastre-se</a>
                        <a href="" data-reveal-id="modal-login">Faça login</a>
                        {% endif %}
                        <a href="">Como usar</a>
                        <a href="">Termos e Condições</a>
                    </li>
                    <li>
                        <ul class="social-list">
                            {% if social.facebook %}
                            <li>
                                <a class="fa fa-facebook" href="{{ social.facebook }}"></a>
                            </li>
                            {% endif %}
                            {% if social.instagram %}
                            <li>
                                <a class="fa fa-instagram" href="{{ social.instagram }}"></a>
                            </li>
                            {% endif %}
                            {% if social.twitter %}
                            <li>
                                <a class="fa fa-twitter" href="{{ social.twitter }}"></a>
                            </li>
                            {% endif %}
                            {% if social.youtube %}
                            <li>
                                <a class="fa fa-youtube" href="{{ social.youtube }}"></a>
                            </li>
                            {% endif %}
                        </ul>

                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="copyright">
        <div class="row">
            <div class="large-12 medium-12 small-12 columns text-center">
                <p>2015 © Copyright. Todos os direitos reservados</p>
            </div>
        </div>
    </div>
</footer>

wsgi/pratosocial/templates/elements/header.html
<header class="nav-header">
    <div class="row">
        <div class="large-3 medium-3 small-12 columns">
            <div class="menu-logo">
                <a href="{% url 'home' %}" class="logo">
                    {% if 'detalhe' in request.path %}
                    <img src="{{ STATIC_URL }}img/icons/logo-interna.png" height="49" width="270" alt="">
                    {% else %}
                    <img src="{{ STATIC_URL }}img/icons/logo-home.png" height="49" width="270" alt="">
                    {% endif %}
                </a>
            </div>
        </div>
        <a id="menu-show-mobile"> <i class="fa fa-bars"></i></a>
        <div class="large-9 medium-12 small-12 columns">
            <div class="menu-header">
                <ul class="menu">
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'contact' %}">contato</a></li>
                    {% if not user.is_authenticated %}
                    <li>
                        <a href="" data-reveal-id="modal-login">login</a>
                        <div id="modal-login" class="reveal-modal text-center small" data-reveal  aria-hidden="true" role="dialog">
                            <p class="lead">Faça seu login</p>
                            <form method="post" action="{% url 'home' %}" class="consult-car" data-abide>{% csrf_token %}
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-envelope"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_login-email" name="login-email" type="email" placeholder="Email" required>
                                        <small class="error">Digite seu email</small>
                                    </div>
                                </div>
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-lock"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_login-password" name="login-password" type="password" placeholder="Senha" required>
                                        <small class="error">Digite sua senha</small>
                                    </div>
                                </div>
                                <button type="submit" class="button small expand">Entrar</button>
                                <input id="id_remember_me" name="remember_me" type="checkbox">
                                <label for="remember_me">Mantenha-me conectado</label>
                            </form>
                            <div id="forgot-password" class="forgot-password">
                                <a href="{% url 'password_reset' %}">Esqueci minha senha</a>
                            </div>
                            <hr>
                            <p class="lead">ou faça login com</p>
                            <ul class="social-list acc">
                                <li>
                                    <a class="fa fa-facebook" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"></a>
                                </li>
                                <li>
                                    <a class="fa fa-instagram" href="{% url 'social:begin' 'instagram' %}?next={{ request.path }}"></a>
                                </li>
                                <li>
                                    <a class="fa fa-google" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"></a>
                                </li>
                            </ul>
                            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
                        </div>
                    </li>
                    <li>
                        <a href="" data-reveal-id="modal-cadastrar">cadastre-se</a>
                        <div id="modal-cadastrar" class="reveal-modal text-center small" data-reveal  aria-hidden="true" role="dialog">
                            <p class="lead">Faça seu cadastro</p>
                            <form method="post" action="{% url 'home' %}" data-abide>
                                {% csrf_token %}
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-user"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_signin-username" name="signin-username" type="text" placeholder="Nome e sobrenome" required>
                                        <small class="error">Digite nome e sobrenome</small>
                                    </div>
                                </div>
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-envelope"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_signin-email" name="signin-email" type="email" placeholder="Email" required>
                                        <small class="error">Digite um email válido</small>
                                    </div>
                                </div>
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-lock"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_signin-password1" name="signin-password1" type="password" placeholder="Senha" required>
                                        <small class="error">Digite uma senha</small>
                                    </div>
                                </div>
                                <div class="row collapse">
                                    <div class="small-4 large-4 columns">
                                        <span class="prefix"><i class="fa fa-lock"></i></span>
                                    </div>
                                    <div class="small-8 large-8 columns">
                                        <input id="id_signin-password2" name="signin-password2" type="password" placeholder="Confirmar senha" required>
                                        <small class="error">Confiurme sua senha</small>
                                    </div>
                                </div>
                                <button type="submit" class="button small expand">Entrar</button>
                            </form>
                            <hr>
                            <p class="lead">ou faça cadastre-se com</p>
                            <ul class="social-list acc">
                                <li>
                                    <a class="fa fa-facebook" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"></a>
                                </li>
{#                                <li>#}
{#                                    <a class="fa fa-instagram" href="{% url 'social:begin' 'instagram' %}?next={{ request.path }}"></a>#}
{#                                </li>#}
                                <li>
                                    <a class="fa fa-google" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"></a>
                                </li>
                            </ul>
                            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="logado">
                        <a href="{% url 'dashboard' request.user.id %}" title="Perfil">
                            {% if request.user.get_photo_thumb %}
                            <img src="{{ request.user.get_photo_thumb }}" alt="{{ request.user.username }}">
                            {% else %}
                            <img src="{{ STATIC_URL }}img/icons/user.png" alt="{{ request.user.username }}">
                            {% endif %}
                            <span>{{ request.user.username }} <i class="fa fa-gear icon-right"></i></span>
                        </a>
                    </li>
                    <li><a href="{% url 'logout' %}">sair</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</header>

wsgi/pratosocial/templates/elements/messages.html
    {% if messages %}
    <div class="row">
        <div class="large-12 medium-12 small-12 columns ">
            {% for message in messages %}
              <div data-alert class="alert-box {{ message.tags }} radius">
                {{ message }}
                <a href="#" class="close">&times;</a>
              </div>
            {% endfor %}
        </div>
     </div>
    {% endif %}

wsgi/pratosocial/templates/elements/sidebar_social.html
{% if social.facebook %}
    <div class="widget-social hide-for-small">
        <div class="fb-page" data-href="{{ social.facebook }}" data-width="370"
             data-hide-cover="false" data-show-facepile="true" data-show-posts="false">
            <div class="fb-xfbml-parse-ignore">
                <blockquote cite="{{ social.facebook }}"><a
                        href="{{ social.facebook }}">Facebook</a></blockquote>
            </div>
        </div>
    </div>
{% endif %}

{% if social.snapwidget %}
    <div class="widget widget-social hide-for-small">
        <!-- SnapWidget -->
        <h4 class="box-title fa fa-instagram">Nosso <span>instagram</span></h4>
        {{ social.snapwidget|safe }}
    </div>
{% endif %}